title: Bug Report
name: Bug Report
description: Create a report to help us reproduce and fix the bug
labels: ["bug"]

body:
- type: markdown
  attributes:
    value: |
      #### Thank you for contributing! 
      - Before reporting a bug, please have a look at the [FAQ](https://github.com/open-ssn/open-ssn/wiki/FAQ) 
      - make sure the issue has no duplicate and hasn't been already addressed by searching through [the existing and past issues](https://github.com/open-ssn/open-ssn/issues?page=1&q=is%3Aissue+sort%3Acreated-desc).

- type: textarea
  attributes:
    label: System Information
    description: |
      Please provide the following system information to help us diagnose the bug. 
      
      - Open SSN version
      - Operating System / Platform
      - Python version
      
      For example:
      Open SSN version: 1.0.0
      Operating System / Platform: Ubuntu 20.04
      Python version: 3.9.6
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: |
      Please provide a clear and concise description of what the bug is and paste the error log below.
      It helps improving readability if the error log is wrapped in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.

      ```
      # error log
      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduce
    description: |
      The steps to reproduce the behavior:
      Please provide a minimal example to help us reproduce the bug.
      Code should be wrapped with ```` ```triple quotes blocks``` ```` to improve readability.
      If the code is too long, please attach as a file or create and link a public gist: https://gist.github.com.

    placeholder: |
      ```python
      # sample code to reproduce the bug
      ```
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Issue submission checklist
    options:
      - label: I report the issue, it's not a question
        required: true
      - label: I checked the problem with documentation, FAQ, open issues, etc and have not found any solution
        required: true
      - label: I updated to the latest Open SSN version and the issue is still there
